### ISSUE TITLE
trimadapter.py Error

### ISSUE THREAD

**Issue by ice4prince** [UCSC-LoweLab/tRAX#13]
Dear Maintainer,
I got an error as follows when running trimadapter.py
`(trax_env) [s205236@Nucleus005 trax_env]$ trimadapters.py --runname ~/IP_R1 --runfile ~/runfile_IP.txt --singleend
Sample_IP_CTL trimmed
Traceback (most recent call last):
  File "/home2/s205236/git/tRAX/trimadapters.py", line 284, in <module>
    cutadaptcounts[samplename], errinfo = readcutadapt(caoutput)
  File "/home2/s205236/git/tRAX/trimadapters.py", line 108, in readcutadapt
    cutadaptcounts["trimmed"] = trimmed - discard
UnboundLocalError: local variable 'trimmed' referenced before assignment`

I checked my pacakge list in this env and found cutadapt 1.18 is truly here.
cutadapt                  1.18             py27h14c3975_1    bioconda

Would you please do me a favor?

**Comment by andrewdholmes** [comment]
OK it looks like there was some trouble reading the cutadapt output, there should be a file there called "IP_R1_log.txt" that contains the cutadapt output, and in that some "=== Summary ===" sections, if you could send me one of those I could take a look at it.
