### ISSUE TITLE
Provide route to output non-tRNA reads and unmapped reads.

### ISSUE THREAD

**Issue by ribonucleo** [UCSC-LoweLab/tRAX#14]

**Comment by patriciaplchan** [comment]
Reads mapped to non-tRNA genomic regions are included in the output BAM files. Unmapped reads are not currently included. We will mark that as a feature request.

**Comment by andrewdholmes** [comment]
If you want the unmapped reads you can look at the bowtie2 commands in the -mapstats.info file and run those adding the --un-gz argument manually.  non-tRNA reads are included in the .bam files and analyzed the other output, mature tRNAs can be identified by their chromosome name which will be the name of the tRNA and filtered out.
