### ISSUE TITLE
rRNA reads classified as others

### ISSUE THREAD

**Issue by Kec89** [UCSC-LoweLab/tRAX#16]
Hi Andrew,

I used the human genomic fasta and gtf annotation you suggested, but I am having an issue regarding the reads classified as "others". In my case I know they are rRNA reads, and I would like them to be classified as such. I thought the issue was related to where on the genome rRNAs are annotated, so I tried different fasta/gtf combinations but nothing worked so far. Do you have any suggestion? This problem is particularly important as reads classified as "others" do not seem to  contribute to the normalization factors DeSeq2 estimates. Do you know how can I make them contribute to DeSeq2?

Thanks for your great work and help!
Tea

**Comment by patriciaplchan** [comment]
Hi Tea,

The GTF file defines the non-tRNA transcripts to be included in the analysis. For your case, it seems like the GTF file does not include the annotations of those rRNAs that you are interested. You may want to add those annotations manually in the GTF file and rerun the analysis. tRAX uses ENSEMBLE formatted GTF file. So long as your file follows the same format, tRAX should work accordingly.

best,
Patricia

**Comment by andrewdholmes** [comment]
If you have a bed file or a set of bed files with these features you can
use the --bedfiles option to include those features in addition to the GTF
file features.  Each bed file will count as it's own gene type in
downstream analyses

**Comment by Kec89** [comment]
Thanks Patricia and Andrew!

Il giorno mar 6 apr 2021 alle ore 22:52 andrewdholmes <
***@***.***> ha scritto:

> If you have a bed file or a set of bed files with these features you can
> use the --bedfiles option to include those features in addition to the GTF
> file features. Each bed file will count as it's own gene type in
> downstream analyses
>
