### ISSUE TITLE
Processsamples.py error 

### ISSUE THREAD

**Issue by sg4640** [UCSC-LoweLab/tRAX#17]
Hi, I'm getting this error message when running the third step of the tRAX pipeline. I also got this type of error when running the TestRun.bash script, so it can't just be my input files. Has anyone else had this issue? Bit of a newbie to tRNA analysis and these sort of pipelines. 
<img width="1324" alt="Screen Shot 2021-04-26 at 2 12 24 PM" src="https://user-images.githubusercontent.com/68067388/116130708-8b2b2600-a699-11eb-8d9b-0618b63152c0.png">

**Comment by andrewdholmes** [comment]
It looks like the tRNA database creation failed, did that produce any error
messages?

**Comment by sg4640** [comment]
This is from the test data that comes with the package. I got this error: 
<img width="387" alt="Screen Shot 2021-04-27 at 1 56 15 PM" src="https://user-images.githubusercontent.com/68067388/116289378-6f3e8780-a760-11eb-8f98-4222b08d1121.png">

**Comment by andrewdholmes** [comment]
OK not sure but it looks like bowtie2-build failed due to a lack of memory
on your machine, if you're running it on a laptop you might need to move
this to a server

**Comment by sg4640** [comment]
Thanks! I'll try that and let you know if I run into any other issues
