### ISSUE TITLE
OS Error 

### ISSUE THREAD

**Issue by bm-153** [UCSC-LoweLab/tRAX#3]
Hi Andrew, 

I'm trying to build a tRNA db and I keep getting the following error and I can't figure out why: 

> Traceback (most recent call last):
>   File "maketrnadb.py", line 83, in <module>
>     getmaturetrnas.main(trnascan=[scanfile], genome=genomefile,gtrnafa=gtrnafafile,namemap=namemapfile, bedfile=dbname+"-maturetRNAs.bed",maturetrnatable=dbname+"-trnatable.txt",trnaalignment=dbname+"-trnaalign.stk",locibed=dbname+"-trnaloci.bed",maturetrnafa=dbname+"-maturetRNAs.fa")
>   File "/mnt/data/BMOHAMED/TRAX_17062019/tRAX-master/getmaturetrnas.py", line 129, in main
>     cmrun = subprocess.Popen(cmcommand, stdout = devnull)
>   File "/home/bmohamed/miniconda2/lib/python2.7/subprocess.py", line 394, in __init__
>     errread, errwrite)
>   File "/home/bmohamed/miniconda2/lib/python2.7/subprocess.py", line 1047, in _execute_child
>     raise child_exception
> OSError: [Errno 2] No such file or directory

I used the following command: 

> python maketrnadb.py --databasename=hg38_nov2019 --genomefile=hg38genome_ucsc_nov2019.fa --trnascanfile=hg38-tRNAs-detailed.out --gtrnafafile=hg38-tRNAs.fa

Thanks in advance!

**Comment by andrewdholmes** [comment]
Alright that looks like it could be a problem with the Infernal install,
can you run 'cmalign'?  If you can't then you can install infernal and get
a working version of cmalign in your path.

Andrew Holmes

**Comment by bm-153** [comment]
Thanks Andrew. I fixed the problem by downloading infernal through conda. 

I've now got the following new error:

```
Traceback (most recent call last):
  File "maketrnadb.py", line 83, in <module>
    getmaturetrnas.main(trnascan=[scanfile], genome=genomefile,gtrnafa=gtrnafafile,namemap=namemapfile, bedfile=dbname+"-maturetRNAs.bed",maturetrnatable=dbname+"-trnatable.txt",trnaalignment=dbname+"-trnaalign.stk",locibed=dbname+"-trnaloci.bed",maturetrnafa=dbname+"-maturetRNAs.fa")
  File "/mnt/data/BMOHAMED/TRAX_nov2019/tRAX-master/getmaturetrnas.py", line 71, in main
    trnascantrnas.extend(readtRNAscan(currfile, genomefile))
  File "/mnt/data/BMOHAMED/TRAX_nov2019/tRAX-master/parsetrnas.py", line 236, in readtRNAscan
    yield tRNAlocus(trnas[curr], trnaseqs[curr], trnascore[curr],trnaamino[curr],trnaanticodon[curr],intronseq[curr], introns)
NameError: global name 'introns' is not defined
```
I was using the previous TRAX release. The above error occurred when I downloaded the latest release. 

Thanks in Advance!

**Comment by andrewdholmes** [comment]
OK that's an issue that you should be able to avoid if you use either the
--namemap options or the --gtrnafafile option to provide the tRNA names.
I'll work on an update so that works regardless, but you probably want to
use one of those options anyways so you can use the official tRNA names.

Andrew Holmes
