### ISSUE TITLE
Location of BAM files if already pre-mapped

### ISSUE THREAD

**Issue by emm13** [UCSC-LoweLab/tRAX#4]
Hi Andrew, 

Thank you for your lovely piece of software and really easy to follow set of instructions. I am doing a custom mapping of my samples and want to provide these custom BAM files to your analysis pipeline for downstream tRNA stats. 

From what I can see the option "--lazyremap" should do this but I don't know how to indicate to the scripts as to where my BAM files are. Intuitively, this would be in the samples.txt file. I tried replacing the fastq files with BAM files and that didn't work. I have tried a couple of directories of BAM files - one in the running directory and one where the fastq files are and neither works. The script just remaps the entire set again.

I'm sorry if I'm being a bit stupid here and overlooking something obvious. Could you please advise on how to proceed ?

**Comment by andrewdholmes** [comment]
The bam files are put in the current working directory and are named with
the sample name (first field in the samples.txt file) followed by .bam.

They also should have a @PG bam header line with " PN:TRAX" in it, but if
that's missing then the whole program should just abort early, not
overwrite.

Andrew Holmes

**Comment by emm13** [comment]
Dear Andrew, 

Super - thanks so much for your quick reply!

Manasa
