### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by bm-153** [UCSC-LoweLab/tRAX#8]
Hi Andrew, 

Came across a weird error when trying to run the processsampes.py program. Had a go in trying to figure out the problem to no success. 

Just some background, I'm doing a tRNA-seq run on some cell samples but there are no conditions (just the one set of samples), and hence no pairfile.txt file supplied. I've done this a few times before and never had a problem until now. Also, I'm using the TRAX program I downloaded in Nov2019. 

Thanks in advance! 

I ran the following command:

`time python processsamples.py --experimentname=HEK293_2ndatt --databasename=hg38_nov2019_new --samplefile=samplefile_HEK293.txt --ensemblgtf=hg38-genes_ensembl2019.gtf --makehub --maketdr --lazyremap 2>&1 | tee HEK293comparison_logoutput.txt`

I got the following error message: 

```
Rscript /mnt/data/USER/TRAX_nov2019/tRAX-master/checkRmodules.R
Mapping Reads
Skipping HEK293_rep1
Skipping HEK293_rep2
Skipping HEK293_rep3
Skipping HEK293_rep4
Rscript /mnt/data/USER/TRAX_nov2019/tRAX-master//featuretypes.R HEK293_2ndatt/HEK293_2ndatt-mapinfo.txt HEK293_2ndatt/HEK293_2ndatt-mapinfo.pdf
Counting Reads
Analyzing counts
Rscript /mnt/data/USER/TRAX_nov2019/tRAX-master//analyzecounts.R HEK293_2ndatt HEK293_2ndatt/HEK293_2ndatt-counts.txt samplefile_HEK293.txt
R script /mnt/data/USER/TRAX_nov2019/tRAX-master//analyzecounts.R failed
Check Rlog.txt for details
Counting Read Types
Traceback (most recent call last):
  File "processsamples.py", line 429, in <module>
    counttypes(samplefilename, trnainfo,expinfo, ensgtf, bedfiles, ignoresizefactors = nosizefactors)
  File "processsamples.py", line 147, in counttypes
    countreadtypes.main(sizefactors=expinfo.sizefactors,combinereps= True ,samplefile=samplefile,maturetrnas=[trnainfo.maturetrnas],trnatable=trnainfo.trnatable,trnaaminofile=expinfo.trnaaminofile,ensemblgtf=ensgtf,trnaloci=[trnainfo.locifile],countfile=expinfo.genetypecounts,realcountfile=expinfo.genetyperealcounts,bedfile= bedfiles,readlengthfile =  expinfo.trnalengthfile )
  File "/mnt/data/USER/TRAX_nov2019/tRAX-master/countreadtypes.py", line 28, in main
    sizefactor = getsizefactors(argdict["sizefactors"]) 
  File "/mnt/data/USER/TRAX_nov2019/tRAX-master/trnasequtils.py", line 379, in getsizefactors
    sizefactorfile = open(sizefactorfile)
IOError: [Errno 2] No such file or directory: 'HEK293_2ndatt/HEK293_2ndatt-SizeFactors.txt'
```

**Comment by andrewdholmes** [comment]
Running it with only one kind of sample type can cause issues with DESeq2
that I use to normalize and possibly some of the plotting as well, even if
they are from one condition you probably want to give them at least 2
separate arbitrary samples.
